### ISSUE TITLE
the installation problem

### ISSUE THREAD

**Issue by xqchen2016** [byavv/angular2-elastic#7]
According to the README.md:
Install:

``` bash
npm install -g typings webpack webpack-dev-server
npm install
```

Build:

``` bash
npm run build
```

Start in dev mode (available on [localhost:3030](localhost:3030) by default)

``` bush
npm run dev
```

can not install successfully.I want to know the reason ..

**Comment by byavv** [comment]
I need more info to handle it, but I met some error before, which happened because of npm cache in case of angular 2 install on top of previous versions. If you get  something like "Unexpected token '\u0000'" , try 

``` bash
npm cache clean
```

Updated to beta.13.
